package com.codekrypt.greendao.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LOG".
 */
@Entity
public class LOG {

    @Id
    private Long id;

    @NotNull
    private String text;

    @Generated
    public LOG() {
    }

    public LOG(Long id) {
        this.id = id;
    }

    @Generated
    public LOG(Long id, String text) {
        this.id = id;
        this.text = text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(@NotNull String text) {
        this.text = text;
    }

}
