package com.codekrypt.greendao.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MEAL".
 */
@Entity
public class Meal {

    @Id
    private Long id;
    private double price;
    private double tip;
    private int stars;

    @NotNull
    private String restaurant_name;
    private int month;
    private int day;
    private int hour;
    private int minute;
    private int year;

    @Generated
    public Meal() {
    }

    public Meal(Long id) {
        this.id = id;
    }

    @Generated
    public Meal(Long id, double price, double tip, int stars, String restaurant_name, int month, int day, int hour, int minute, int year) {
        this.id = id;
        this.price = price;
        this.tip = tip;
        this.stars = stars;
        this.restaurant_name = restaurant_name;
        this.month = month;
        this.day = day;
        this.hour = hour;
        this.minute = minute;
        this.year = year;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public double getTip() {
        return tip;
    }

    public void setTip(double tip) {
        this.tip = tip;
    }

    public int getStars() {
        return stars;
    }

    public void setStars(int stars) {
        this.stars = stars;
    }

    @NotNull
    public String getRestaurant_name() {
        return restaurant_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRestaurant_name(@NotNull String restaurant_name) {
        this.restaurant_name = restaurant_name;
    }

    public int getMonth() {
        return month;
    }

    public void setMonth(int month) {
        this.month = month;
    }

    public int getDay() {
        return day;
    }

    public void setDay(int day) {
        this.day = day;
    }

    public int getHour() {
        return hour;
    }

    public void setHour(int hour) {
        this.hour = hour;
    }

    public int getMinute() {
        return minute;
    }

    public void setMinute(int minute) {
        this.minute = minute;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

}
